noremap j h
noremap k j
noremap l k
noremap ; l


" Cursor shape:
" 2 = block
" 4 = underline
" 6 = vertical bar

" different cursor shapes in insert mode
let &t_SI = "\<Esc>[5 q" "SI = insert mode, blinking vertical bar
let &t_SR = "\<Esc>[4 q" "SR = replace mode, solid underscore
let &t_EI = "\<Esc>[2 q" "EI = normal mode, solid block

augroup CursorShape
  autocmd!
  autocmd VimEnter,InsertLeave,VimResume * silent! !printf '\033[2 q'
  autocmd InsertEnter * silent! !printf '\033[6 q'
  autocmd VimLeave * silent! !printf '\033[2 q'
augroup END

set nu rnu 

highlight LineNr ctermfg=99 guifg=#6F68DD
highlight CursorLineNr ctermfg=99 guifg=#6F68DD

set autoindent
set expandtab
set tabstop=4
set shiftwidth=4

set ignorecase
set mouse=a

set undofile
set undodir=~/.vim/undo//
